/**
 * Generated ESM shims for the `@termco/*` runtime surface
 * (src/core/runtime/registry.ts).
 *
 * An import map maps `@termco/<name>` → `termco-plugin://__runtime/<name>`;
 * this module answers that reserved host with a tiny module that resolves the
 * host's LIVE instance out of `globalThis.__termcoRuntime`:
 *
 *     const load = globalThis.__termcoRuntime?.["react"];
 *     export default await load();
 *
 * Only a DEFAULT export is emitted, deliberately: named exports would have to
 * be known statically here, which would duplicate every module's export list
 * into the main process and rot. The plugin build rewrites named imports into
 * destructuring instead (`scripts/plugin-compiler-lib.mjs`), and
 * hand-written plugins use `import ns from "@termco/react"`.
 *
 * `__runtime` is safe as a reserved host: plugin ids may not contain
 * underscores (PLUGIN_ID_RE in pluginScheme.ts), so it can never collide.
 */

/** Reserved URL host that serves runtime shims instead of plugin files. */
export const RUNTIME_HOST = "__runtime";

/**
 * Module specifiers are used inside a JS string literal AND must match the
 * registry keys. Anything else is refused rather than interpolated.
 */
const SAFE_SPECIFIER = /^[A-Za-z0-9@][A-Za-z0-9@._/-]*$/;

export function isSafeRuntimeSpecifier(name: string): boolean {
  if (!name || name.length > 200) return false;
  if (!SAFE_SPECIFIER.test(name)) return false;
  return !name.split("/").includes("..");
}

/**
 * Build the shim source for one runtime specifier, or null when the specifier
 * is malformed (→ 403). Whether the module actually exists is decided at
 * RUNTIME by the registry, so the error names the specifier and the fix.
 */
export function runtimeShimSource(name: string): string | null {
  if (!isSafeRuntimeSpecifier(name)) return null;
  const spec = JSON.stringify(name);
  return `// Generated by Termco (electron/main/core/runtimeShim.ts) — do not edit.
const registry = globalThis.__termcoRuntime;
if (!registry) {
  throw new Error(
    'Termco runtime is not installed yet: "@termco/' + ${spec} + '" was imported before the app finished booting.'
  );
}
const load = registry[${spec}];
if (!load) {
  throw new Error(
    'Unknown Termco runtime module "@termco/' + ${spec} + '". See src/core/runtime/registry.ts for the available surface.'
  );
}
export default await load();
`;
}

/**
 * Parse `termco-plugin://__runtime/<name>` into its specifier, or null when the
 * URL targets a different host. It is parsed by hand because the WHATWG parser
 * resolves dot-segments silently.
 */
export function runtimeSpecifierFromUrl(url: string): string | null {
  const m = /^termco-plugin:\/\/([^/?#]+)(\/[^?#]*)?(?:[?#].*)?$/.exec(url);
  if (!m || m[1] !== RUNTIME_HOST) return null;
  let name: string;
  try {
    name = decodeURIComponent(m[2] ?? "");
  } catch {
    return null;
  }
  name = name.replace(/^\/+/, "");
  // The import map's prefix mapping cannot append an extension, so specifiers
  // arrive bare; tolerate an explicit .js for hand-written URLs.
  name = name.replace(/\.js$/, "");
  return name || null;
}
